import type { OrdersResponse } from "./types";

export const ORDERS_STATIC_DATA: OrdersResponse = {
  summary: {
    totalOrders: 5523,
    statCards: [
      {
        id: "doneOrder",
        label: "Done Order",
        count: 3056,
        changeLabel: "from last month",
        progressPercent: 72,
        progressColor: "#F74608",
        icon: "check",
      },
      {
        id: "onTheWay",
        label: "On The Way",
        count: 1535,
        changeLabel: "3.5% from last month",
        progressPercent: 58,
        progressColor: "#6BA3D6",
        icon: "truck",
      },
      {
        id: "orderRejected",
        label: "Order Rejected",
        count: 929,
        changeLabel: "+2.3% from last month",
        progressPercent: 45,
        progressColor: "#D69E2E",
        icon: "x",
      },
    ],
  },
  orders: [
    {
      id: "ORD-5533",
      referenceId: "8F4A2B1C",
      customer: {
        name: "Abdullah Al Noman",
        email: "abdullah@gmail.com",
        phone: "+8801712-345678",
        avatarUrl: "https://i.pravatar.cc/150?u=abdullah",
      },
      date: "2026-05-12T10:30:00",
      itemCount: 3,
      paymentMethod: "COD",
      amount: 339,
      status: "Pending",
    },
    {
      id: "ORD-5528",
      referenceId: "2C9D7E4A",
      customer: {
        name: "Fatema Begum",
        email: "fatema@gmail.com",
        phone: "+8801912-987654",
        avatarUrl: "https://i.pravatar.cc/150?u=fatema",
      },
      date: "2026-05-11T14:15:00",
      itemCount: 5,
      paymentMethod: "Nagad",
      amount: 410,
      status: "Done",
    },
    {
      id: "ORD-5521",
      referenceId: "5B1A3F8D",
      customer: {
        name: "Karim Uddin",
        email: "karim@gmail.com",
        phone: "+8801612-456789",
        avatarUrl: "https://i.pravatar.cc/150?u=karim",
      },
      date: "2026-05-10T09:45:00",
      itemCount: 2,
      paymentMethod: "Bkash",
      amount: 299,
      status: "Pending",
    },
    {
      id: "ORD-5517",
      referenceId: "9E6C2A4F",
      customer: {
        name: "Sumaiya Akter",
        email: "sumaiya@gmail.com",
        phone: "+8801812-234567",
        avatarUrl: "https://i.pravatar.cc/150?u=sumaiya",
      },
      date: "2026-05-09T16:20:00",
      itemCount: 4,
      paymentMethod: "COD",
      amount: 362,
      status: "Processing",
    },
    {
      id: "ORD-5512",
      referenceId: "1D8F5B7C",
      customer: {
        name: "Rahim Mia",
        email: "rahim@gmail.com",
        phone: "+8801512-876543",
        avatarUrl: "https://i.pravatar.cc/150?u=rahim",
      },
      date: "2026-05-08T11:00:00",
      itemCount: 1,
      paymentMethod: "Bkash",
      amount: 155,
      status: "Rejected",
    },
    {
      id: "ORD-5505",
      referenceId: "7A3E9D2B",
      customer: {
        name: "Nusrat Jahan",
        email: "nusrat@gmail.com",
        phone: "+8801712-112233",
        avatarUrl: "https://i.pravatar.cc/150?u=nusrat",
      },
      date: "2026-05-07T13:30:00",
      itemCount: 6,
      paymentMethod: "SSLCommerz",
      amount: 530,
      status: "Done",
    },
    {
      id: "ORD-5501",
      referenceId: "4F2B8C6E",
      customer: {
        name: "Hasan Mahmud",
        email: "hasan@gmail.com",
        phone: "+8801912-445566",
        avatarUrl: "https://i.pravatar.cc/150?u=hasan",
      },
      date: "2026-05-06T08:50:00",
      itemCount: 2,
      paymentMethod: "Nagad",
      amount: 275,
      status: "Processing",
    },
    {
      id: "ORD-5498",
      referenceId: "6C1A9F3D",
      customer: {
        name: "Tamanna Sultana",
        email: "tamanna@gmail.com",
        phone: "+8801612-778899",
        avatarUrl: "https://i.pravatar.cc/150?u=tamanna",
      },
      date: "2026-05-05T17:10:00",
      itemCount: 3,
      paymentMethod: "COD",
      amount: 198,
      status: "Done",
    },
  ],
};
