import type { BillingPageData } from "./billing.types";

export const BILLING_STATIC_DATA: BillingPageData = {
  paymentMethods: [
    {
      id: "pm-1",
      provider: "bkash",
      label: "Bkash",
      accountNumber: "01726512261",
      isPrimary: true,
    },
    {
      id: "pm-2",
      provider: "nagad",
      label: "Nagad",
      accountNumber: "01726512261",
      isPrimary: false,
    },
    {
      id: "pm-3",
      provider: "nagad",
      label: "Nagad",
      accountNumber: "01726512261",
      isPrimary: false,
    },
    {
      id: "pm-4",
      provider: "nagad",
      label: "Nagad",
      accountNumber: "01726512261",
      isPrimary: false,
    },
  ],
  billingInformation: {
    fullName: "Tarikul Islam",
    phone: "01726512261",
    email: "tarikulislamtanvir85@gmail.com",
    billingCycle: "monthly",
  },
  paymentHistory: [
    {
      id: "txn-1",
      date: "16 May, 2026",
      description: "Growth • Monthly renewal",
      amount: "৳2,499",
      method: "bkash",
      methodLabel: "Bkash",
      transactionId: "BK2026X>XXX",
      status: "paid",
    },
    {
      id: "txn-2",
      date: "16 Apr, 2026",
      description: "Growth • Monthly renewal",
      amount: "৳2,499",
      method: "bkash",
      methodLabel: "Bkash",
      transactionId: "BK2026X>XXX",
      status: "paid",
    },
    {
      id: "txn-3",
      date: "16 Mar, 2026",
      description: "Growth • Monthly renewal",
      amount: "৳2,499",
      method: "bkash",
      methodLabel: "Bkash",
      transactionId: "BK2026X>XXX",
      status: "paid",
    },
    {
      id: "txn-4",
      date: "16 Feb, 2026",
      description: "Starter • Monthly renewal",
      amount: "৳999",
      method: "nagad",
      methodLabel: "Nagad",
      transactionId: "BK2026X>XXX",
      status: "paid",
    },
  ],
};
