import type { SecurityPageData } from "./security.types";

export const SECURITY_STATIC_DATA: SecurityPageData = {
  settings: {
    twoFactorEnabled: true,
    newDeviceLoginAlert: true,
    sessionTimeout: false,
  },
  activities: [
    {
      id: "1",
      deviceName: 'MacBook Pro 14"',
      deviceMeta: "macOS - Chrome",
      deviceType: "laptop",
      location: "Dhaka, Bangladesh",
      countryCode: "BD",
      ipAddress: "103.191.12.45",
      lastActive: "Currently Active",
      lastActiveHighlight: true,
      status: "this-device",
      showActions: false,
    },
    {
      id: "2",
      deviceName: "Windows PC",
      deviceMeta: "Windows 11 - Chrome",
      deviceType: "desktop",
      location: "Chattogram, Bangladesh",
      countryCode: "BD",
      ipAddress: "45.130.22.10",
      lastActive: "Today, 10:24 AM",
      status: "active",
      showActions: true,
    },
    {
      id: "3",
      deviceName: "iOS • Safari",
      deviceMeta: "iOS • Safari",
      deviceType: "mobile",
      location: "Dhaka, Bangladesh",
      countryCode: "BD",
      ipAddress: "103.191.12.88",
      lastActive: "Yesterday, 9:15 PM",
      status: "active",
      showActions: true,
    },
    {
      id: "4",
      deviceName: "Unknown Device",
      deviceMeta: "Windows • Edge",
      deviceType: "unknown",
      location: "Barisal, Bangladesh",
      countryCode: "BD",
      ipAddress: "203.125.66.77",
      lastActive: "May 19, 2025, 8:30 PM",
      status: "logged-out",
      showActions: false,
    },
  ],
};
